# Clean the three main datasets used by Countries
Each dataset display the countries differently

Will pull what the countries are, and then find a common ground to convert all of them

In [ ]:
import pandas as pd

In [ ]:
# Get the datasets
map_df = pd.read_csv("../../map/Cleaned_1000_Swapped_Books.csv")
popularity_df = pd.read_csv("../../popularity/books_cleaned_genresV2.csv")
dashboard_Age_df = pd.read_csv("../Combined_BookRec_GenreToAge.csv")
dashboard_Gender_df = pd.read_csv("../Combined_GlobalReader_GenreToGender_V2.csv")

In [ ]:
# display(map_df)
display(dashboard_Age_df)
# display(dashboard_Gender_df)

In [ ]:
# Get all the countries in a list for map_df
map_Countries = set()

# Loop through all the records' genre
for record in map_df['most_popular_country']:
    map_Countries.add(record)
    
display(map_Countries)

In [ ]:
# Get all the countries in a list for dashboard_age_df
# View all the genres available
dashboard_Age_Countries = set()

# Loop through all the records' genre
for record in dashboard_Age_df['Country']:
    dashboard_Age_Countries.add(record)
    
display(dashboard_Age_Countries)

In [ ]:
# Get all the countries in a list for dashboard_gender_df
# View all the genres available
dashboard_Gender_Countries = set()

# Loop through all the records' genre
for record in dashboard_Gender_df['Country']:
    dashboard_Gender_Countries.add(record)
    
display(dashboard_Gender_Countries)

In [ ]:
# List of countries standardized

country_map = {
    "us": "United States", "usa": "United States", "united states": "United States",
    "canada": "Canada",
    "mexico": "Mexico",
    "panama": "Panama",
    "dominican republic": "Dominican Republic",
    "haiti": "Haiti",

    "uk": "United Kingdom", "united kingdom": "United Kingdom", "great britain": "United Kingdom",
    "ireland": "Ireland",
    "germany": "Germany",
    "france": "France",
    "italy": "Italy",
    "spain": "Spain",
    "portugal": "Portugal",
    "netherlands": "Netherlands",
    "belgium": "Belgium",
    "austria": "Austria",
    "sweden": "Sweden",
    "switzerland": "Switzerland",
    "denmark": "Denmark",
    "norway": "Norway",
    "poland": "Poland",
    "romania": "Romania",
    "russia": "Russia",
    "czech republic": "Czech Republic",
    "greece": "Greece",
    "estonia": "Estonia",

    "australia": "Australia",
    "new zealand": "New Zealand",
    "japan": "Japan",
    "china": "China",
    "taiwan": "Taiwan",
    "south korea": "South Korea",
    "hong kong sar china": "Hong Kong", "hong kong": "Hong Kong",
    "singapore": "Singapore",
    "philippines": "Philippines",
    "thailand": "Thailand",
    "vietnam": "Vietnam",
    "malaysia": "Malaysia",
    "india": "India",

    "iran": "Iran",
    "israel": "Israel",
    "lebanon": "Lebanon",
    "qatar": "Qatar",
    "saudi arabia": "Saudi Arabia",
    "bahrain": "Bahrain",
    "egypt": "Egypt",
    "ghana": "Ghana",
    "nigeria": "Nigeria",
    "south africa": "South Africa",

    "brazil": "Brazil",
    "argentina": "Argentina",
    "chile": "Chile",
    "colombia": "Colombia",
    "venezuela": "Venezuela"
};

In [49]:
print(map_df["most_popular_country"])


def GetGeneralCountries(keywords):
    # Check what value the genre could be and convert it to the general general
    cleaned_keyword = keywords.lower().strip()
    if cleaned_keyword in country_map:
        country = country_map[cleaned_keyword] 
        return country
            
    return ""

0       UK
1      USA
2       UK
3      USA
4       UK
      ...
985    USA
986    USA
987    USA
988     US
989     US
Name: most_popular_country, Length: 990, dtype: str

Set the countries for the Map DF

In [ ]:
country_map_df = map_df.copy()
country_map_df['most_popular_country'] = country_map_df['most_popular_country'].apply(GetGeneralCountries)
display(country_map_df)

Set the coutnries for the dashboard age

In [47]:
print(dashboard_Age_df["Country"])

0                   usa
1                   usa
2               romania
3                   usa
4        united kingdom
             ...
1677                usa
1678        netherlands
1679                usa
1680                usa
1681                usa
Name: Country, Length: 1682, dtype: str

In [50]:
country_dashboard_age_df = dashboard_Age_df.copy()
country_dashboard_age_df['Country'] = country_dashboard_age_df['Country'].apply(GetGeneralCountries)
display(country_dashboard_age_df)

,User_ID,Age,Country,ISBN,Title,Author,Main_Genres,Genres,Age_Group
0,254,24,United States,399501487,Lord of the Flies,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
1,254,24,United States,440419468,Holes,Louis Sachar,Children's Books,Crime & Thriller,Young Adult (18-29)
2,384,23,Romania,156528207,The Little Prince,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues",Young Adult (18-29)
3,882,23,United States,553255851,Where the Red Fern Grows,Wilson Rawls,Children's Books,Historical Fiction,Young Adult (18-29)
4,1025,33,United Kingdom,394404289,The Prophet,Kahlil Gibran,Literature & Fiction,Classic Fiction,Adult (30-59)
...,...,...,...,...,...,...,...,...,...
1677,277427,48,United States,553274295,Where the Red Fern Grows,Wilson Rawls,Children's Books,Historical Fiction,Adult (30-59)
1678,277478,31,Netherlands,425067645,Icebreaker,HANNAH GRACE,Sports,Winter Sports,Adult (30-59)
1679,277639,48,United States,553121456,Independence,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences,Adult (30-59)
1680,277764,18,United States,399501487,Lord of the Flies,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
1681,278843,28,United States,440477093,The Secret Garden,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests",Young Adult (18-29)

Get the dashboard Gender countries in

In [51]:
country_dashboard_gender_df = dashboard_Gender_df.copy()
country_dashboard_gender_df['Country'] = country_dashboard_gender_df['Country'].apply(GetGeneralCountries)
display(country_dashboard_gender_df)

,User_ID,Country,Gender,Genres
0,b068d3fde4f776a079090282cff262d55c95aae5f5a763...,United States,female,Young Adult
1,124bdafe2f71ea17c52e4938766fcaa64c28a6ed5cb75c...,United States,female,Non-Fiction
2,124bdafe2f71ea17c52e4938766fcaa64c28a6ed5cb75c...,United States,female,Non-Fiction
3,124bdafe2f71ea17c52e4938766fcaa64c28a6ed5cb75c...,United States,female,Art/Literature
4,124bdafe2f71ea17c52e4938766fcaa64c28a6ed5cb75c...,United States,female,Art/Literature
...,...,...,...,...
2557,0a04ce257449eecbf594eba73c570707fc2d92b79dbc4b...,Saudi Arabia,female,Fantasy
2558,0a04ce257449eecbf594eba73c570707fc2d92b79dbc4b...,Saudi Arabia,female,Mystery/Thriller
2559,0a04ce257449eecbf594eba73c570707fc2d92b79dbc4b...,Saudi Arabia,female,Sci-Fi
2560,0a04ce257449eecbf594eba73c570707fc2d92b79dbc4b...,Saudi Arabia,female,Sci-Fi
2561,b881952a3095cf6374856258dda1d89052358635159736...,Philippines,female,Graphic Novels/Manga

In [ ]:
# Save them all 
country_map_df.to_csv("../../map/Cleaned_1000_Swapped_Books_V2.csv")
country_dashboard_age_df.to_csv("../Combined_BookRec_GenreToAge_V2.csv")
country_dashboard_gender_df.to_csv("../Combined_GlobalReader_GenreToGender_V3.csv")